set -ga terminal-overrides ",xterm-256color*:Tc"
set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB,xterm-256color:RGB"
set -g set-clipboard on
set -as terminal-features ",xterm-256color:clipboard"
set -g extended-keys on
set -g extended-keys-format csi-u
set -s escape-time 0
# ----------------------------=== Colors ===--------------------------
thm_bg="#1a1a1a"
thm_fg="#bbbbbb"
thm_gray="bbbbbb"
thm_cyan="#56b6c2"
thm_magenta="#c678dd"
thm_red="#e06c75"
thm_green="#98c379"
thm_blue="#61afef"
thm_yellow="#e5c07b"
thm_black="#1a1a1a"
thm_black4="#1a1a1a"

# ----------------------------=== Theme ===--------------------------

# status
set -g status-interval 1
set -g escape-time 10
set -g focus-events on
set -g status "on"
set -g status-bg "${thm_black}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

# messages
set -g message-style fg="${thm_cyan}",bg="${thm_black}",align="centre"
set -g message-command-style fg="${thm_cyan}",bg="${thm_black}",align="centre"

# panes
set -g pane-border-style fg="${thm_black}"
set -g pane-active-border-style fg="${thm_blue}"

# windows
setw -g window-status-activity-style fg="${thm_fg}",bg="${thm_bg}",none
setw -g window-status-separator ""
setw -g window-status-style fg="${thm_fg}",bg="${thm_bg}",none

# statusline
set -g status-left ""
set -g status-right "#[fg=$thm_green,bg=$thm_black,nobold,nounderscore,noitalics] #[fg=$thm_bg,bg=$thm_green,nobold,nounderscore,noitalics]  #[fg=$thm_fg,bg=$thm_black] #{b:pane_current_path} #{?client_prefix,#[fg=$thm_red],#[fg=$thm_yellow]}#[bg=$thm_black] #{?client_prefix,#[bg=$thm_red],#[bg=$thm_yellow]}#[fg=$thm_bg]  #[fg=$thm_fg,bg=$thm_black] #S #[fg=$thm_blue,bg=$thm_black,nobold,nounderscore,noitalics] #[fg=$thm_bg,bg=$thm_blue,nobold,nounderscore,noitalics]  #[fg=$thm_fg,bg=$thm_black] %m-%d %H:%M "

# current_dir
setw -g window-status-format "#[fg=$thm_bg,bg=$thm_blue] #I #[fg=$thm_fg,bg=$thm_bg] #W "
setw -g window-status-current-format "#[fg=$thm_bg,bg=$thm_yellow] #I #[fg=$thm_fg,bold,bg=$thm_bg] #W "

# modes
setw -g clock-mode-colour "${thm_blue}"
setw -g mode-style "fg=${thm_green} bg=${thm_black4} bold"

# ----------------------------=== Theme ===--------------------------

#unbind C-b
#set-option -g prefix C-a
#bind-key C-a send-prefix

#unbind %
#bind | split-window -h

#unbind '"'
#bind - split-window -v

bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5
bind -r Right resize-pane -R 5
bind -r Left resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
bind C-u copy-mode -u

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

# tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions between system restart
set -g @plugin 'tmux-plugins/tmux-continuum' # auto-saves tmux sessions
set -g @continuum-save-interval '5'
set -g @continuum-restore 'on'
set -g @resurrect-hook-post-save-all 'sed -i -e "/\tgeneral\t/d" -e "/\t[0-9][0-9]*\t/d" "$(readlink -f ~/.local/share/tmux/resurrect/last)"'


#run '~/.tmux/plugins/tpm/tpm'
# this is where the debian package installed it
run '/usr/share/tmux-plugin-manager/tpm'
