#Change the default prompt format
format = """\
[╭╴](#e09d6c)$env_var\
$all[╰─](#e09d6c)$character"""
# 
# Change the default prompt characters
[character]
success_symbol = "[](#e09d6c)"
error_symbol = "[](#e09d6c)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path](#e09d6c)[$read_only]($read_only_style) "

[python]
format = "[ $version]($style) "
style = "bold green"
