#Change the default prompt format
format = """\
[╭╴](#61afef)$env_var\
$all[╰─](#61afef)$character"""
# 
# Change the default prompt characters
[character]
success_symbol = "[](#61afef)"
error_symbol = "[](#61afef)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path](#61afef)[$read_only]($read_only_style) "

[python]
format = "[ $version]($style) "
style = "bold green"
