require("tyler.core.options")
require("tyler.core.keymaps")
require("tyler.plugins-setup")
require("tyler.plugins.bufferline")
require("tyler.plugins.lualine")
require("tyler.plugins.telescope")
require("tyler.plugins.treesitter")
